# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  jassoncodesapi:
    image: jassoncodesapi
    container_name: api_container
    build:
      context: .
      dockerfile: src/Jasson.Codes.Api/Dockerfile
    depends_on:
      jassoncodesapi.db:
        condition: service_started
        restart: true
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:5001;http://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=JassonCodesApi
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/aspnetapp.pfx
    volumes:
      - api:/certs:ro

  jassoncodesapi.db:
    container_name: api_postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ResumeAppDB
    volumes:
      - api_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5452:80"
    volumes:
      - api_db_pgdamdmin:/etc/pgadmin4

volumes:
  api:
    name: jassoncodesapi
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certs
  api_db:
    name: jassoncodesapi_db
  api_db_pgdamdmin:
      name: api_db_pgdamdmin